code-insiders --install-extension bierner.lit-html
code-insiders --install-extension chriseckenrode.vscode-chester-atom
code-insiders --install-extension CoenraadS.bracket-pair-colorizer
code-insiders --install-extension eamodio.gitlens
code-insiders --install-extension eg2.tslint
code-insiders --install-extension esbenp.prettier-vscode
code-insiders --install-extension idleberg.applescript
code-insiders --install-extension joaompinto.vscode-graphviz
code-insiders --install-extension sdras.night-owl
code-insiders --install-extension stkb.rewrap
code-insiders --install-extension stringham.move-ts
code-insiders --install-extension wesbos.theme-cobalt2
