code-insiders --install-extension aaron-bond.better-comments
code-insiders --install-extension aaronthomas.vscode-snazzy-operator
code-insiders --install-extension chiragpat.tomorrow-and-tomorrow-night-operator-mono-theme
code-insiders --install-extension christian-kohler.npm-intellisense
code-insiders --install-extension CoenraadS.bracket-pair-colorizer
code-insiders --install-extension eamodio.gitlens
code-insiders --install-extension eg2.tslint
code-insiders --install-extension eg2.vscode-npm-script
code-insiders --install-extension esbenp.prettier-vscode
code-insiders --install-extension formulahendry.auto-rename-tag
code-insiders --install-extension idleberg.applescript
code-insiders --install-extension jvitor83.types-autoinstaller
code-insiders --install-extension ms-vsliveshare.vsliveshare
code-insiders --install-extension pnp.polacode
code-insiders --install-extension quicktype.quicktype
code-insiders --install-extension sdras.night-owl
code-insiders --install-extension Stephanvs.dot
code-insiders --install-extension stkb.rewrap
code-insiders --install-extension wesbos.theme-cobalt2
code-insiders --install-extension wix.vscode-import-cost
